// ui/src/components/Terminal.tsx
import { useEffect, useRef } from "react";
import { Terminal as XTerm } from "@xterm/xterm";
import { FitAddon } from "@xterm/addon-fit";
import "@xterm/xterm/css/xterm.css";

interface TerminalProps {
  websocketUrl: string;
  onClose?: () => void;
}

export function Terminal({ websocketUrl, onClose }: TerminalProps) {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!containerRef.current) return;

    const term = new XTerm({ cursorBlink: true, fontSize: 14, theme: { background: "#111110", foreground: "#e8e4de" } });
    const fitAddon = new FitAddon();
    term.loadAddon(fitAddon);
    term.open(containerRef.current);
    fitAddon.fit();

    const ws = new WebSocket(websocketUrl);
    ws.binaryType = "arraybuffer";

    ws.onopen = () => {
      term.onData((data) => ws.send(data));
    };
    ws.onmessage = (event) => {
      const data = event.data;
      if (typeof data === "string") {
        term.write(data);
      } else {
        term.write(new Uint8Array(data as ArrayBuffer));
      }
    };
    ws.onclose = () => {
      term.write("\r\n[Connection closed]\r\n");
    };

    const onResize = () => fitAddon.fit();
    window.addEventListener("resize", onResize);

    return () => {
      window.removeEventListener("resize", onResize);
      ws.close();
      term.dispose();
    };
  }, [websocketUrl]);

  return (
    <div style={{ position: "relative" }}>
      {onClose && (
        <button onClick={onClose} style={{ position: "absolute", top: 4, right: 4, zIndex: 10, background: "var(--bg-tertiary)", color: "var(--text-primary)", border: "1px solid var(--border-primary)", borderRadius: 4, padding: "2px 8px", cursor: "pointer" }}>
          Close
        </button>
      )}
      <div ref={containerRef} style={{ height: 400, background: "#111110", borderRadius: 6 }} />
    </div>
  );
}

// ui/src/lib/components/Terminal.svelte
<script lang="ts">
	import { onMount, onDestroy } from 'svelte';

	let {
		execId = '',
		onDisconnect = () => {}
	}: {
		execId: string;
		onDisconnect?: () => void;
	} = $props();

	let terminalEl: HTMLDivElement;
	let term: any;
	let fitAddon: any;
	let ws: WebSocket | null = null;

	onMount(async () => {
		const { Terminal } = await import('@xterm/xterm');
		const { FitAddon } = await import('@xterm/addon-fit');
		await import('@xterm/xterm/css/xterm.css');

		fitAddon = new FitAddon();
		term = new Terminal({
			cursorBlink: true,
			fontSize: 14,
			fontFamily: 'JetBrains Mono, Menlo, Monaco, Consolas, monospace',
			theme: {
				background: '#0f172a',
				foreground: '#e2e8f0',
				cursor: '#f59e0b',
				selectionBackground: '#334155',
			}
		});

		term.loadAddon(fitAddon);
		term.open(terminalEl);
		fitAddon.fit();

		const proto = location.protocol === 'https:' ? 'wss:' : 'ws:';
		ws = new WebSocket(`${proto}//${location.host}/ws/exec/${execId}`);
		ws.binaryType = 'arraybuffer';

		ws.onopen = () => {
			const dims = { type: 'resize', cols: term.cols, rows: term.rows };
			ws!.send(JSON.stringify(dims));
		};

		ws.onmessage = (e) => {
			if (e.data instanceof ArrayBuffer) {
				term.write(new Uint8Array(e.data));
			} else {
				term.write(e.data);
			}
		};

		ws.onclose = () => {
			term.write('\r\n\x1b[33m[Session ended]\x1b[0m\r\n');
			onDisconnect();
		};

		term.onData((data: string) => {
			if (ws && ws.readyState === WebSocket.OPEN) {
				ws.send(data);
			}
		});

		term.onResize(({ cols, rows }: { cols: number; rows: number }) => {
			if (ws && ws.readyState === WebSocket.OPEN) {
				ws.send(JSON.stringify({ type: 'resize', cols, rows }));
			}
		});

		const resizeObs = new ResizeObserver(() => fitAddon?.fit());
		resizeObs.observe(terminalEl);

		return () => resizeObs.disconnect();
	});

	onDestroy(() => {
		ws?.close();
		term?.dispose();
	});
</script>

<div bind:this={terminalEl} class="w-full h-full min-h-[400px] rounded-lg overflow-hidden"></div>
